### ISSUE TITLE
Get 404 from v2 api's

### ISSUE THREAD

**Issue by javadghane** [sut-it/Sadjad-API#1]
Hi, thanks for this great api. :1st_place_medal: 
today i test this api: 
https://api.sadjad.ac.ir/v2/stu/profile?username=aaaa&password=bbbbb

and i get 404 Sorry, the page you are looking for could not be found. :( 
is any problem happen to api server?

**Comment by sky93** [comment]
Thanks for getting in touch. Just letting you know due to unspecified circumstances, the official Sadjad University of Technology's API system is not providing any services relating to `stu.sadjad.ac.ir` website anymore. As much as we want you to enjoy the benefits of the service we offer, there is no opportunity to do so at this time.

We will update you once we have new information on this matter. Thank you for your understanding.
